{% set name = "npe2" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 33a520f75c22ada5b77ef2fa75ebdee7ff3fed4000f56b3939930a8286b067a1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - npe2 = npe2.cli:main

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
    - hatch-vcs
  run:
    - appdirs
    - python-build
    - psygnal >=0.3.0
    - pydantic <2.0
    - python >=3.8
    - pytomlpp
    - pyyaml
    - rich
    - typer

test:
  imports:
    - npe2
  requires:
    - pip
  commands:
    - pip check
    - npe2 --help

about:
  home: https://github.com/napari/npe2
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Second generation napari plugin engine
  doc_url: https://napari.org/
  dev_url: https://github.com/napari/npe2

extra:
  recipe-maintainers:
    - tlambert03
    - nclack
    - sofroniewn
    - jni
