{% set name = "npe2" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3d3d43b99bbd3b189fedd7313589c89642a4af0f14b24b9763eb134ba6a5548c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - npe2 = npe2.cli:main

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm
  run:
    - appdirs
    - build
    - magicgui >=0.3.3
    - psygnal >=0.3.0
    - pydantic
    - python >=3.8
    - pytomlpp
    - pyyaml
    - typer

test:
  imports:
    - npe2
  requires:
    - pip
  commands:
    - pip check
    - npe2 --help

about:
  home: https://github.com/napari/npe2
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Second generation napari plugin engine
  doc_url: https://napari.org/
  dev_url: https://github.com/napari/npe2

extra:
  recipe-maintainers:
    - tlambert03
    - nclack
    - sofroniewn
    - jni
