{% set name = "npe2" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 90c21d50e0e10cf6b4bd4930e10c066730335cdcac9cde9409aadcdb3612d50c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - npe2 = npe2.cli:main

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm
  run:
    - python >=3.7
    - pyyaml
    - intervaltree
    - magicgui >=0.3.3
    - napari-plugin-engine
    - psygnal
    - pydantic
    - appdirs
    - pytomlpp
    - typer
    - importlib-metadata >=1.5.0  # not needed for py>37 but keeping for noarch

test:
  imports:
    - npe2
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/napari/npe2
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Second generation napari plugin engine
  doc_url: https://napari.org/
  dev_url: https://github.com/napari/npe2

extra:
  recipe-maintainers:
    - tlambert03
    - nclack
    - sofroniewn
    - jni
